# Site settings
name: 快乐 就在你的心 的博客
email: kljzndx@outlook.com
author: 李继龙
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/kljzndx
baseurl: "/My-Blog"
description: Actually, less is more!
meta_description: 李继龙;个人博客;快乐就在你的心
#motto: It's our wits that make us men.
banner: 快乐就在你的心

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kljzndx
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light