markdown: kramdown
permalink: /:title.html
url: https://kljzndx.github.io/My-Blog/
lsi: true
rouge: true
safe: true

# presonal config
title: 快乐就在你的心的博客
feed: /atom.xml
comments: disqus

author:
  name: likebeta
  nickname: likebeta
  email: ixxoo.me@gmail.com
  gmail: ixxoo.me@gmail.com
  qqmail: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=GnZzcX94f257WmtrNHl1dw
  qqlist: http://list.qq.com/cgi-bin/qf_invite?id=eff06957927177ae5d491bb3c18e4a3c5fc328c95b6ae04f
  site: https://www.ixxoo.me

seo:
  keyword:
  description:
